Fulgurio\SocialNetworkBundle\Entity\User:
  type: mappedSuperclass
  repositoryClass: Fulgurio\SocialNetworkBundle\Repository\UserRepository
  table: member
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    avatar:
      type: string
      length: 255
      nullable: true
    send_msg_to_email:
      type: boolean
    created_at:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update
