Fulgurio\SocialNetworkBundle\Entity\User:
  type: mappedSuperclass
#  type: entity
  repositoryClass: Fulgurio\SocialNetworkBundle\Repository\UserRepository
  table: member
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    avatar:
      type: string
      length: 255
      nullable: true
    send_msg_to_email:
      type: boolean
    created_at:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated_at:
      type: datetime
      gedmo:
        timestampable:
          on: update

  oneToMany:
    friends:
      targetEntity: Fulgurio\SocialNetworkBundle\Entity\UserFriendship
      mappedBy: user_tgt
    msgSender:
      targetEntity: Message
      mappedBy: sender
    msgTarget:
      targetEntity: MessageTarget
      mappedBy: target
