services:
    fulgurio_social_network.twig.login_form_extension:
        class: Fulgurio\SocialNetworkBundle\Twig\Extension\LoginFormExtension
        tags:
            -  { name: twig.extension }
        arguments:
            session:       "@session"
            csrf_provider: "@form.csrf_provider"

    fulgurio_social_network.twig.avatar_extension:
        class: Fulgurio\SocialNetworkBundle\Twig\Extension\AvatarExtension
        tags:
            -  { name: twig.extension }

    fulgurio_social_network.registration.form.type:
        class: Fulgurio\SocialNetworkBundle\Form\Type\RegistrationFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: fulgurio_social_network_registration }

    fulgurio_social_network.resetting.form.type:
        class: Fulgurio\SocialNetworkBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: fulgurio_social_network_resetting }

    fulgurio_social_network.profile.form.type:
        class: Fulgurio\SocialNetworkBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: fulgurio_social_network_profile }
        arguments: [ %fos_user.model.user.class% ]

    # Admin Mailer
    fulgurio_social_network.admin_mailer:
        class: Fulgurio\SocialNetworkBundle\Mailer\AdminMailer
        arguments:
            0: "@mailer"
            1: "@router"
            2: "@templating"
            3:
                contact.from               : %fulgurio_social_network.admin_email_contact.from%
                contact.textTemplate       : %fulgurio_social_network.admin_email_contact.text%
                contact.htmlTemplate       : %fulgurio_social_network.admin_email_contact.html%
                remove_avatar.from         : %fulgurio_social_network.admin_email_remove_avatar.from%
                remove_avatar.subject      : %fulgurio_social_network.admin_email_remove_avatar.subject%
                remove_avatar.textTemplate : %fulgurio_social_network.admin_email_remove_avatar.text%
                remove_avatar.htmlTemplate : %fulgurio_social_network.admin_email_remove_avatar.html%
