services:
    fulgurio_social_network.twig.login_form_extension:
        class: Fulgurio\SocialNetworkBundle\Twig\Extension\LoginFormExtension
        tags:
            -  { name: twig.extension }
        arguments:
            session:       "@session"
            csrf_provider: "@form.csrf_provider"

    fulgurio_social_network.twig.avatar_extension:
        class: Fulgurio\SocialNetworkBundle\Twig\Extension\AvatarExtension
        tags:
            -  { name: twig.extension }

    fulgurio_social_network.registration.form.type:
        class: Fulgurio\SocialNetworkBundle\Form\Type\RegistrationFormType
        arguments: [ %fos_user.model.user.class% ]
        tags:
            - { name: form.type, alias: fulgurio_social_network_registration }

    fulgurio_social_network.resetting.form.type:
        class: Fulgurio\SocialNetworkBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: fulgurio_social_network_resetting }

    fulgurio_social_network.profile.form.type:
        class: Fulgurio\SocialNetworkBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: fulgurio_social_network_profile }
        arguments: [ %fos_user.model.user.class% ]
