fulgurio_social_network_friendship_add:
    pattern:  /add
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:add }

fulgurio_social_network_friendship_invit:
    pattern:  /{userId}/invit
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:invit }

fulgurio_social_network_friendship_accept:
    pattern:  /{userId}/accept
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:accept }

fulgurio_social_network_friendship_refuse:
    pattern:  /{userId}/refuse
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:refuse }

fulgurio_social_network_friendship_profil:
    pattern:  /{userId}/show
    defaults: { _controller: FulgurioSocialNetworkBundle:Profile:show }

fulgurio_social_network_friendship_search_to_add:
    pattern:  /searchToAdd
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:searchToAdd }

fulgurio_social_network_friendship_search:
    pattern:  /search
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:search }

fulgurio_social_network_friendship_list:
    pattern:  /
    defaults: { _controller: FulgurioSocialNetworkBundle:Friendship:list }
