fulgurio_social_network_admin_users:
    pattern:  /admin/users/
    defaults: { _controller: FulgurioSocialNetworkBundle:AdminUser:list }

fulgurio_social_network_admin_users_ban:
    pattern:  /admin/users/{userId}/ban
    defaults: { _controller: FulgurioSocialNetworkBundle:AdminUser:ban }

fulgurio_social_network_admin_users_unban:
    pattern:  /admin/users/{userId}/unban
    defaults: { _controller: FulgurioSocialNetworkBundle:AdminUser:ban }

fulgurio_social_network_admin_users_view:
    pattern:  /admin/users/{userId}/view
    defaults: { _controller: FulgurioSocialNetworkBundle:AdminUser:view }